[package]
name = "wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
rayon = "1.10.0"
wasm-bindgen = "0.2"
wasm-bindgen-rayon = { version = "1.3.0", features = ["no-bundler"] }
web-sys = "0.3.76"

[profile.release]
opt-level = 3
